# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: europe-west1-docker.pkg.dev/{{PROJECT_ID}}/ride-sharing/trip-service
          ports:
            - containerPort: 9093
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: uri
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: uri
        - name: OSRM_API
          valueFrom:
            secretKeyRef:
              name: external-apis
              key: osrm

        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: JAEGER_ENDPOINT
              name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip-service
  ports:
    - port: 9093
      name: grpc
      targetPort: 9093
  type: ClusterIP
