# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: ride-sharing/driver-service
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: grpc
  selector:
    app: driver-service
