# @format

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials

type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: stripe-secrets
#
#type: Opaque
#stringData:
# add your Stripe secret key here
